site_name: Poema IX
theme:
  name: material
  # name: flatly
  custom_dir: static
extra_css:
  - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - Poema IX: index.md
  - PoP List: PoP-List.md
  # - (EN): Poema-IX-EN.md
  - Virtual IXP: Virtual-IXP.md
  - Members: members.md
  - Route Server: RS.md
  - Poema Network: "https://net.kskb.eu.org"
site_url: https://ix.poema.eu.org/
repo_url: https://github.com/KSKBpage/KSKB-IX
edit_uri: blob/main/docs/
plugins:
  - search:
      separator: '[\s\u200b\-]'
