site_name: KSKB-IX
theme:
  # name: material
  name: flatly
  custom_dir: static
extra_css:
  - css/hidefooter.css
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.extra
nav:
  - Poema IX: index.md
  - Poema IX(EN): Poema-IX-EN.md
  - Virtual IXP: Virtual-IXP.md
  - Members: members.md
  - Route Server Configuration: RS.md
  - Poema Network: "https://net.kskb.eu.org"
site_url: https://ix.poema.eu.org/
repo_url: https://github.com/KSKBpage/KSKB-IX
edit_uri: blob/main/docs/
