vars: {
  d2-legend: {
    near: bottom-left
    a <-> b: Backbone interconnection, VXLAN-EVPN {
      style.stroke: "#4a9eff"
    }
    a <-> b: Leaf node connection, GRETAP/OVPN {
      style.stroke: "#b46eff"
    }
    a.style.opacity: 0
    b.style.opacity: 0
  }
}
